services:
  web-dmz:
    build:
      context: ..
      dockerfile: http.Dockerfile
    container_name: apache-dmz
    network_mode: "host"
    volumes:
      - ./config:/etc/apache2/sites-enabled
      - ./html:/var/www
