services:
  web-intranet:
    build:
      context: ..
      dockerfile: http.Dockerfile
    container_name: apache-intranet
    network_mode: "host"
    volumes:
      - ./config:/etc/apache2/sites-enabled
      - ./html:/var/www
      - ./certs:/etc/ssl/certs_empresa
